# Custom rubocop configuration

AllCops:
  DisplayCopNames: true
  Exclude:
  - deepl-rb.gemspec
  - vendor/**/*

Metrics/BlockLength:
  Exclude:
  - "**/*_spec.rb"

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self
